version: '3.9'

services:
  app:
    image: maksonik/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test

  caddy:
    image: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - services/caddy::/etc/caddy