name: ci

on:
  push:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app

      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build app

      - name: Push Docker image
        run: docker-compose -f docker-compose.yml push app
